# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f4845829e30d0be7cf4fff9c7b1a718d9c658d0d888e536c36ffc36c76a1ba83b6c5aadcef512043394a9e7a7220adf10b3aeb3306c0f67ccff317481b438ec1

test:
  secret_key_base: 0e80164fcdab1e4cc8fb8c1012cfed8102279f2678dd50f982f2fab0aa27f29648b07496678910e662396b72e67c26e6181b91927ad3cbe7e6f133b1137ec3ee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
